kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: src/192.168.0.101:3010/roe/gotgbot

steps:
- name: test
  image: golang
  commands:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go build