kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: gotgbot

steps:
- name: test
  image: golang
  commands:
  - echo $GOPATH
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - echo Haliluiya
  - echo $DRONE_GIT_HTTP_URL
  - echo $DRONE_REPO
  - echo $DRONE_REMOTE_URL
  - echo $DRONE_REPO_LINK
  - echo $DRONE_GIT_SSH_URL
  - go build
