kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: src/DRONE_REPO

steps:
- name: run_tests
  image: golang
  settings:
    CONFIG_TG_TOKEN:
      from_secret: CONFIG_TG_TOKEN
    CONFIG_DB_HOST:
      from_secret: CONFIG_DB_HOST
    CONFIG_DB_USERNAME:
      from_secret: CONFIG_DB_USERNAME
    CONFIG_DB_NAME:
      from_secret: CONFIG_DB_NAME
    CONFIG_DB_PASSWORD:
      from_secret: CONFIG_DB_PASSWORD
    
  commands:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - sed -e "s/example_token/$CONFIG_TG_TOKEN/g" -e "s/example_host/$CONFIG_DB_HOST/g" -e "s/example_user/$CONFIG_DB_USERNAME/g" -e "s/example_database/$CONFIG_DB_NAME/g" -e "s/example_password/$CONFIG_DB_PASSWORD/g" config.json.example > config.json
  - go test
  - go build
